version: '3.8'
services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    expose:
      - 3306
# docker compose -p node-reactjs-v2 up -d
